// Chess opening repertoire for a 1500-1600 chess.com rapid player (10|0).
//
// Design philosophy:
//  - Minimize rote memorization, maximize understanding of plans & pawn structures.
//  - Choose openings that produce middlegames you can navigate on the clock.
//  - White: 1.e4 Italian complex (Giuoco Pianissimo) + low-theory anti-Sicilian (Alapin)
//           + Advance vs French & Caro-Kann.
//  - Black vs 1.e4: Accelerated Dragon (one core idea: the ...d5 break).
//  - Black vs 1.d4: Nimzo-Indian, with the Bogo-Indian when White avoids 3.Nc3.
//
// DATA MODEL
//  Each chapter holds one or more complete "lines" (full move sequences from move 1).
//  The app merges lines that share a prefix into a single study tree, so you only
//  need to read the new ideas at each branch point. `san` = the move in algebraic
//  notation; `c` = the explanation shown when that move appears. Empty `c` on a
//  shared prefix move means "see the first line that introduced it".

export const REPERTOIRE = {
  groups: [
    // =====================================================================
    //  WHITE: 1.e4 — the Italian complex
    // =====================================================================
    {
      id: "white",
      title: "White: 1.e4 (Italian Complex)",
      heroColor: "w",
      blurb: "A complete 1.e4 repertoire built on the slow Italian. Sound, flexible, and light on forced theory — you get rich middlegames where understanding beats memorization.",
      chapters: [
        {
          id: "w-italian-main",
          title: "Italian — Giuoco Pianissimo (3...Bc5)",
          intro: "The backbone of your White repertoire. After 3.Bc4 Bc5 we play the 'quiet Italian' with c3 and d3. Plan: complete development (Nbd2, O-O, Re1, Bb3), tuck the king away, then reroute the knight Nb1-d2-f1-g3 and prepare the central break d3-d4 at the right moment. You are never worse and you always understand the position.",
          lines: [
            { name: "Main plan", moves: [
              { san: "e4", c: "1.e4 — grab the center and open lines for the bishop and queen." },
              { san: "e5", c: "" },
              { san: "Nf3", c: "Develop with a threat (attacks e5) — always a good rule." },
              { san: "Nc6", c: "" },
              { san: "Bc4", c: "The Italian bishop, eyeing the f7 weak point." },
              { san: "Bc5", c: "Black mirrors. Now we choose the slow, strategic setup." },
              { san: "c3", c: "Prepares d4 and gives the bishop a retreat to c2 after a later ...Na5." },
              { san: "Nf6", c: "" },
              { san: "d3", c: "The 'pianissimo' move. We keep the center solid rather than rushing d4, avoiding all the sharp theory." },
              { san: "d6", c: "" },
              { san: "O-O", c: "King safety first." },
              { san: "O-O", c: "" },
              { san: "Nbd2", c: "Heading for the f1-g3 reroute, eyeing f5 and supporting a future e4-e5 or d3-d4." },
              { san: "a6", c: "Black stops Bb5 and prepares ...Ba7/...b5." },
              { san: "Bb3", c: "Retreating before Black plays ...Na5 to trade your good bishop." },
              { san: "Ba7", c: "" },
              { san: "h3", c: "A key prophylactic move: stops ...Bg4 pinning your knight, and makes luft. Now your plan is Re1, Nf1-g3, and break with d4. You have a comfortable, easy-to-play game." },
            ]},
          ],
        },
        {
          id: "w-two-knights",
          title: "Italian — Two Knights (3...Nf6)",
          intro: "When Black plays 3...Nf6 instead of 3...Bc5, do NOT enter the sharp 4.Ng5 (Fried Liver) tactics — they cut both ways and demand precise memory. Instead play 4.d3, the quiet Italian, and transpose to the same calm structures you already know.",
          lines: [
            { name: "Quiet 4.d3", moves: [
              { san: "e4", c: "" },
              { san: "e5", c: "" },
              { san: "Nf3", c: "" },
              { san: "Nc6", c: "" },
              { san: "Bc4", c: "" },
              { san: "Nf6", c: "The Two Knights. Black invites 4.Ng5 — decline it." },
              { san: "d3", c: "The calm choice. Avoids the Fried Liver entirely and steers into familiar Italian waters." },
              { san: "Bc5", c: "" },
              { san: "c3", c: "Same plan as the main Italian." },
              { san: "d6", c: "" },
              { san: "O-O", c: "" },
              { san: "O-O", c: "" },
              { san: "Nbd2", c: "Reach an identical structure to the Giuoco Pianissimo. Same plans: Bb3, h3, Re1, Nf1-g3, d4." },
            ]},
            { name: "3...Nf6 4...Be7", moves: [
              { san: "e4", c: "" },
              { san: "e5", c: "" },
              { san: "Nf3", c: "" },
              { san: "Nc6", c: "" },
              { san: "Bc4", c: "" },
              { san: "Nf6", c: "" },
              { san: "d3", c: "" },
              { san: "Be7", c: "A more passive bishop placement; you get a free hand in the center." },
              { san: "O-O", c: "" },
              { san: "O-O", c: "" },
              { san: "Re1", c: "Supports e4 and prepares d4." },
              { san: "d6", c: "" },
              { san: "c3", c: "Prepare d4. Because Black's bishop is on e7 (not c5), the d4 break is even easier and you can aim for a small space edge." },
            ]},
          ],
        },
        {
          id: "w-petroff",
          title: "Petroff Defense (2...Nf6)",
          intro: "After 2.Nf3 Nf6 Black counterattacks instead of defending e5. Take the pawn, retreat correctly, and you get an easy game with a small space edge. Know the move-order: after 3.Nxe5 you must answer 3...d6 by retreating, and you must understand why 3...Nxe4 is met by 4.Qe2.",
          lines: [
            { name: "Main 3...d6", moves: [
              { san: "e4", c: "" },
              { san: "e5", c: "" },
              { san: "Nf3", c: "" },
              { san: "Nf6", c: "The Petroff. Black ignores the threat to e5 and hits e4." },
              { san: "Nxe5", c: "Grab the pawn. Now do NOT play Nxf7?? — just sit on e5." },
              { san: "d6", c: "Kicking the knight. The key move to remember." },
              { san: "Nf3", c: "Retreat. (Never Nxf7?! giving up the strong knight for activity Black welcomes.) Now e4 is hanging." },
              { san: "Nxe4", c: "" },
              { san: "d4", c: "Open the center for your better-developed pieces." },
              { san: "d5", c: "" },
              { san: "Bd3", c: "Develop, target the e4 knight and the kingside." },
              { san: "Nc6", c: "" },
              { san: "O-O", c: "You have a slightly freer position and easy development. Plans: Re1, c4, Nc3." },
            ]},
            { name: "Trap: 3...Nxe4", moves: [
              { san: "e4", c: "" },
              { san: "e5", c: "" },
              { san: "Nf3", c: "" },
              { san: "Nf6", c: "" },
              { san: "Nxe5", c: "" },
              { san: "Nxe4", c: "A natural-looking mistake (right move-order is 3...d6 first)." },
              { san: "Qe2", c: "The refutation! Pinning. If 4...Nf6?? 5.Nc6+ wins the queen on a discovered attack." },
              { san: "Qe7", c: "Forced to unpin and offer a trade." },
              { san: "Qxe4", c: "" },
              { san: "d6", c: "" },
              { san: "d4", c: "" },
              { san: "dxe5", c: "" },
              { san: "dxe5", c: "You emerge a clean tempo up with the better structure — a pleasant, near-risk-free edge." },
            ]},
          ],
        },
        {
          id: "w-philidor",
          title: "Philidor & ...d6 setups (2...d6)",
          intro: "After 2...d6 Black plays passively. Strike with 3.d4 to seize a large center and a comfortable, lasting space advantage. This is one of the easiest positions to play in the whole repertoire.",
          lines: [
            { name: "3.d4", moves: [
              { san: "e4", c: "" },
              { san: "e5", c: "" },
              { san: "Nf3", c: "" },
              { san: "d6", c: "The Philidor — solid but passive." },
              { san: "d4", c: "Challenge the center immediately while Black is undeveloped." },
              { san: "exd4", c: "" },
              { san: "Nxd4", c: "A great knight on d4 and more space." },
              { san: "Nf6", c: "" },
              { san: "Nc3", c: "" },
              { san: "Be7", c: "" },
              { san: "Be2", c: "" },
              { san: "O-O", c: "" },
              { san: "O-O", c: "You have more space and easier development. Plans: f4 or Be3/Qd2, Rad1, slow build-up." },
            ]},
          ],
        },
        {
          id: "w-alapin",
          title: "Alapin Sicilian (1...c5 2.c3)",
          intro: "Your anti-Sicilian. Instead of memorizing reams of Open Sicilian theory, play 2.c3, preparing d4 with a big center. The plans are natural and you sidestep all of Black's pet lines. Know the two main replies: 2...Nf6 and 2...d5.",
          lines: [
            { name: "vs 2...Nf6", moves: [
              { san: "e4", c: "" },
              { san: "c5", c: "" },
              { san: "c3", c: "The Alapin. Prepares d4 to build a strong pawn center." },
              { san: "Nf6", c: "Attacking e4, the critical try." },
              { san: "e5", c: "Gain space and kick the knight." },
              { san: "Nd5", c: "" },
              { san: "d4", c: "Build the big center." },
              { san: "cxd4", c: "" },
              { san: "Nf3", c: "Develop before recapturing; keeps options." },
              { san: "Nc6", c: "" },
              { san: "cxd4", c: "" },
              { san: "d6", c: "Black strikes at your e5 spearhead." },
              { san: "Bc4", c: "Develop with tempo on the d5 knight; you stand pleasantly with a strong center. Plans: O-O, Nc3 (after the knight moves) or Bb3/Re1." },
            ]},
            { name: "vs 2...d5", moves: [
              { san: "e4", c: "" },
              { san: "c5", c: "" },
              { san: "c3", c: "" },
              { san: "d5", c: "The other main try — Black challenges e4 at once." },
              { san: "exd5", c: "" },
              { san: "Qxd5", c: "The queen is exposed here (unlike the Scandinavian, c3 hasn't blocked your Nc3... but d4 gains time)." },
              { san: "d4", c: "Gain time later via Nf3/Na3-c2 and open the center." },
              { san: "Nf6", c: "" },
              { san: "Nf3", c: "" },
              { san: "Bg4", c: "" },
              { san: "Be2", c: "Break the pin, prepare to castle." },
              { san: "e6", c: "" },
              { san: "O-O", c: "Comfortable development and central control. Plans: Na3-c2 protecting d4, Be3, h3 questioning the bishop." },
            ]},
          ],
        },
        {
          id: "w-advance-french",
          title: "Advance French (1...e6)",
          intro: "Against the French, grab space with 3.e5. You get a big pawn chain (d4-e5) and a clear plan: defend the base on d4, expand, and use your space. Black will try to break with ...c5 and ...f6 — your job is to hold the chain and keep the bind.",
          lines: [
            { name: "Main", moves: [
              { san: "e4", c: "" },
              { san: "e6", c: "The French Defense." },
              { san: "d4", c: "" },
              { san: "d5", c: "" },
              { san: "e5", c: "The Advance. Gain space and lock Black's light-squared bishop behind the pawn chain — the French 'bad bishop'." },
              { san: "c5", c: "Black hits the base of your chain." },
              { san: "c3", c: "Reinforce d4 — the whole position revolves around this square." },
              { san: "Nc6", c: "" },
              { san: "Nf3", c: "Defend d4 again and develop." },
              { san: "Qb6", c: "Piling on d4 and pressuring b2." },
              { san: "a3", c: "A flexible move: prepares b4 to gain queenside space and defend c5/d4, and gives the queen no targets. (The sharp Milner-Barry gambit with Bd3 is fun but risky — a3 is the safer, plan-based route.)" },
              { san: "c4", c: "Black often locks the queenside, conceding the d4 break for now." },
              { san: "Nbd2", c: "Reroute toward the kingside/queenside; you'll break with b3 to open lines against c4 and use your central space. A pleasant, easy-to-understand middlegame." },
            ]},
          ],
        },
        {
          id: "w-advance-caro",
          title: "Advance Caro-Kann (1...c6)",
          intro: "Against the Caro-Kann, play the Advance with the Short System: e5, Nf3, Be2, O-O, c3, Nbd2. It's calm, low-theory, and easy to play. The point: develop smoothly, leave the c-pawn flexible, and challenge Black's good bishop on f5 with Nh4 or Bd3 ideas later.",
          lines: [
            { name: "Short System", moves: [
              { san: "e4", c: "" },
              { san: "c6", c: "The Caro-Kann." },
              { san: "d4", c: "" },
              { san: "d5", c: "" },
              { san: "e5", c: "The Advance. Unlike the French, Black gets his light bishop OUT first — so we plan to challenge it." },
              { san: "Bf5", c: "The whole point of the Caro: this bishop is active, not bad." },
              { san: "Nf3", c: "Calm development (the Short System), avoiding sharp lines like 4.Nc3/g4." },
              { san: "e6", c: "" },
              { san: "Be2", c: "Modest but flexible. Prepares O-O and a later Nh4 or Bd3 to hit the f5 bishop." },
              { san: "Ne7", c: "Black reroutes the knight toward g6/f5." },
              { san: "O-O", c: "" },
              { san: "h6", c: "Making luft for the bishop." },
              { san: "Nbd2", c: "Develop and prepare c3 (supporting d4) plus Nb3 or Nf1-g3. You have a safe, space-based game; the standard plan is to play on the kingside or push your central majority." },
            ]},
            { name: "...c5 break", moves: [
              { san: "e4", c: "" },
              { san: "c6", c: "" },
              { san: "d4", c: "" },
              { san: "d5", c: "" },
              { san: "e5", c: "" },
              { san: "Bf5", c: "" },
              { san: "Nf3", c: "" },
              { san: "e6", c: "" },
              { san: "Be2", c: "" },
              { san: "c5", c: "The principled break at the base of the chain." },
              { san: "Be3", c: "Calmly defend d4. You are solid; if pawns get traded on d4 you'll get a good knight and pressure on the c-file." },
              { san: "cxd4", c: "" },
              { san: "Nxd4", c: "A strong central knight; you stand comfortably." },
            ]},
          ],
        },
        {
          id: "w-scandinavian",
          title: "Scandinavian (1...d5)",
          intro: "After 1...d5 2.exd5 Qxd5 3.Nc3, you hit the queen with tempo and get a fast, free development. Your plan is simple and effective: d4, Nf3, Bc4/Be2, Bd2 or Be3, then often O-O-O with a lead in development. Black's early queen sortie costs time — punish it by developing quickly.",
          lines: [
            { name: "3...Qa5", moves: [
              { san: "e4", c: "" },
              { san: "d5", c: "The Scandinavian." },
              { san: "exd5", c: "" },
              { san: "Qxd5", c: "" },
              { san: "Nc3", c: "Develop with tempo — the queen must move again." },
              { san: "Qa5", c: "The main retreat, pinning nothing but eyeing the kingside." },
              { san: "d4", c: "Take the full center." },
              { san: "Nf6", c: "" },
              { san: "Nf3", c: "" },
              { san: "c6", c: "Making a luft square (d7/c7) for the queen and supporting ...d5/...Bf5." },
              { san: "Bc4", c: "Active development hitting f7." },
              { san: "Bf5", c: "" },
              { san: "Bd2", c: "Preparing O-O-O and Nd5 ideas, unpinning. You have a clear lead in development and the safer plan: castle queenside and attack." },
            ]},
            { name: "3...Qd6", moves: [
              { san: "e4", c: "" },
              { san: "d5", c: "" },
              { san: "exd5", c: "" },
              { san: "Qxd5", c: "" },
              { san: "Nc3", c: "" },
              { san: "Qd6", c: "A modern, more flexible queen retreat (keeps an eye on e5)." },
              { san: "d4", c: "" },
              { san: "Nf6", c: "" },
              { san: "Nf3", c: "" },
              { san: "a6", c: "Stopping Nb5 ideas hitting the queen." },
              { san: "g3", c: "A clean setup: Bg2, O-O, and pressure the center. You keep your development lead and a small but stable edge." },
            ]},
          ],
        },
        {
          id: "w-pirc-modern",
          title: "Pirc / Modern (1...d6 / 1...g6)",
          intro: "Against these hypermodern setups (Black gives you the center, planning to attack it later), build a classical center and develop soundly: e4, d4, Nc3, Nf3, Be2, O-O. Don't overextend — a healthy big center plus calm development gives you a long-term space edge.",
          lines: [
            { name: "Classical system", moves: [
              { san: "e4", c: "" },
              { san: "d6", c: "The Pirc (1...g6 Modern transposes after ...Nf6/...d6)." },
              { san: "d4", c: "Take the center Black is inviting you to build." },
              { san: "Nf6", c: "" },
              { san: "Nc3", c: "Defend e4 and develop." },
              { san: "g6", c: "" },
              { san: "Nf3", c: "The Classical system — simple and strong. (Avoids the sharp 150 Attack memory work.)" },
              { san: "Bg7", c: "" },
              { san: "Be2", c: "" },
              { san: "O-O", c: "" },
              { san: "O-O", c: "You have a big center and easy development. Plans: h3 (stop ...Bg4/...Ng4), Re1, Be3/Qd2, and decide between e5 expansion or quiet pressure." },
            ]},
          ],
        },
      ],
    },

    // =====================================================================
    //  BLACK vs 1.e4 — Accelerated Dragon
    // =====================================================================
    {
      id: "black-e4",
      title: "Black vs 1.e4: Accelerated Dragon",
      heroColor: "b",
      blurb: "A Sicilian with ONE big idea — the ...d5 freeing break in a single move. You fianchetto the bishop to g7 (raking the long diagonal), castle fast, and aim for active piece play. Far less rote theory than the Najdorf or normal Dragon.",
      chapters: [
        {
          id: "b-accel-main",
          title: "Accelerated Dragon — Main Line (5.Nc3)",
          intro: "The core. After 1.e4 c5 2.Nf3 Nc6 3.d4 cxd4 4.Nxd4 g6, you put the bishop on g7 and castle. The dream is the ...d5 break (equalizing in one move, the whole point of the 'Accelerated' move-order). When White plays the natural 6.Be3/7.Bc4 setup, you castle and prepare ...d6, ...Bd7, ...Rc8 with queenside play.",
          lines: [
            { name: "6.Be3 / 7.Bc4 setup", moves: [
              { san: "e4", c: "" },
              { san: "c5", c: "The Sicilian — fight for the center asymmetrically and play for a win as Black." },
              { san: "Nf3", c: "" },
              { san: "Nc6", c: "" },
              { san: "d4", c: "" },
              { san: "cxd4", c: "" },
              { san: "Nxd4", c: "" },
              { san: "g6", c: "The Accelerated Dragon. By delaying ...Nf6 and ...d6, you keep ...d5-in-one-move available." },
              { san: "Nc3", c: "The Open Sicilian main line." },
              { san: "Bg7", c: "The Dragon bishop — it will rake the long diagonal a1-h8, pressuring d4 and b2." },
              { san: "Be3", c: "White's standard developing move, eyeing a kingside attack." },
              { san: "Nf6", c: "Now develop the knight (White's Be3 stopped the immediate ...d5 trick)." },
              { san: "Bc4", c: "The 'Maroczy-style' bishop, but here without the c4 pawn. Watch for the ...d5 break." },
              { san: "O-O", c: "Castle into safety before committing the center." },
              { san: "Bb3", c: "White tucks the bishop away from ...Na5 tricks." },
              { san: "d6", c: "Solid Dragon structure. Now your plan is ...Bd7, ...Rc8, ...Ne5, and queenside expansion with ...a5-a4 or ...b5." },
              { san: "f3", c: "White supports e4 and prepares Qd2/O-O-O — a kingside pawn storm is coming." },
              { san: "Bd7", c: "Develop, connect, and prepare ...Rc8 + ...Ne5/...a5. It's a race: your queenside play vs his kingside attack — but you understand your plan clearly." },
            ]},
            { name: "The ...d5 break (6.Be2)", moves: [
              { san: "e4", c: "" },
              { san: "c5", c: "" },
              { san: "Nf3", c: "" },
              { san: "Nc6", c: "" },
              { san: "d4", c: "" },
              { san: "cxd4", c: "" },
              { san: "Nxd4", c: "" },
              { san: "g6", c: "" },
              { san: "Nc3", c: "" },
              { san: "Bg7", c: "" },
              { san: "Be2", c: "A natural but slightly passive move that does NOT control d5 — so strike!" },
              { san: "Nf6", c: "Develop and prepare to castle." },
              { san: "O-O", c: "" },
              { san: "O-O", c: "" },
              { san: "Nb3", c: "If White instead allows it, the freeing break appears." },
              { san: "d5", c: "The thematic equalizer! Because White didn't clamp down with c4 or f3/Bc4 in time, this break frees your game completely and you stand at least equal with active pieces." },
            ]},
          ],
        },
        {
          id: "b-maroczy",
          title: "Maroczy Bind (5.c4)",
          intro: "The critical test: White plays c4 to clamp down on the ...d5 break, gaining a big space bind. Don't panic — the Bind is well-understood. Your plan: trade a pair of knights with ...Nxd4, develop the bishop to d7/c6, and slowly pressure the bind with ...a5 (grabbing the c5 square), ...Nd7-c5, and eventually a ...b5 or ...f5 break. Patience and good squares.",
          lines: [
            { name: "Gurgenidze setup", moves: [
              { san: "e4", c: "" },
              { san: "c5", c: "" },
              { san: "Nf3", c: "" },
              { san: "Nc6", c: "" },
              { san: "d4", c: "" },
              { san: "cxd4", c: "" },
              { san: "Nxd4", c: "" },
              { san: "g6", c: "" },
              { san: "c4", c: "The Maroczy Bind — White clamps d5 and takes space. Now it's a strategic battle." },
              { san: "Bg7", c: "" },
              { san: "Be3", c: "" },
              { san: "Nf6", c: "" },
              { san: "Nc3", c: "" },
              { san: "O-O", c: "Get the king safe first." },
              { san: "Be2", c: "" },
              { san: "d6", c: "Solid; prepares ...Bd7 and ...Nxd4." },
              { san: "O-O", c: "" },
              { san: "Bd7", c: "The Gurgenidze plan: develop the bishop to d7 (heading to c6 to fight for the long diagonal and the d5/e4 squares)." },
              { san: "Qd2", c: "" },
              { san: "Nxd4", c: "Trade a pair of knights to relieve your cramped position — the standard freeing idea in the Bind." },
              { san: "Bxd4", c: "" },
              { san: "Bc6", c: "Now ...a5, ...Nd7, and ...Bxd4 (or ...a5-a4) follow. You blockade c5, target c4/e4, and look for the ...b5 or ...f5 break. Cramped but very solid — know the plan and you'll be fine." },
            ]},
          ],
        },
        {
          id: "b-rossolimo",
          title: "Rossolimo (3.Bb5)",
          intro: "A very common anti-Sicilian at club level: 3.Bb5 pins/trades your knight. Answer 3...g6 (staying true to your fianchetto plan). After Bxc6 dxc6 you get the bishop pair and a rock-solid structure; the doubled c-pawns control key central squares (d5/b5). Plan: ...Bg7, ...Nf6, ...O-O, then ...e5 or ...Nd7 with a comfortable, no-risk game.",
          lines: [
            { name: "3...g6 4.Bxc6 dxc6", moves: [
              { san: "e4", c: "" },
              { san: "c5", c: "" },
              { san: "Nf3", c: "" },
              { san: "Nc6", c: "" },
              { san: "Bb5", c: "The Rossolimo — White avoids the Open Sicilian." },
              { san: "g6", c: "Stay on plan: fianchetto." },
              { san: "Bxc6", c: "" },
              { san: "dxc6", c: "Recapture toward the center. You get the bishop pair; the doubled c-pawns are healthy (they cover d5 and b5) and you have an open d-file." },
              { san: "d3", c: "" },
              { san: "Bg7", c: "" },
              { san: "h3", c: "Stopping ...Bg4." },
              { san: "Nf6", c: "" },
              { san: "Nc3", c: "" },
              { san: "O-O", c: "Safe and sound. Plan: ...b6 + ...Be6/...Qe7, or ...Nd7 + ...e5 to seize the center with your bishops. You're at least equal with the two bishops." },
            ]},
            { name: "4.O-O", moves: [
              { san: "e4", c: "" },
              { san: "c5", c: "" },
              { san: "Nf3", c: "" },
              { san: "Nc6", c: "" },
              { san: "Bb5", c: "" },
              { san: "g6", c: "" },
              { san: "O-O", c: "White keeps the bishop instead of trading." },
              { san: "Bg7", c: "" },
              { san: "c3", c: "Preparing d4." },
              { san: "Nf6", c: "Hitting e4 — a useful gain of tempo." },
              { san: "Re1", c: "" },
              { san: "O-O", c: "" },
              { san: "d4", c: "" },
              { san: "cxd4", c: "" },
              { san: "cxd4", c: "" },
              { san: "d5", c: "Strike in the center! With the bishop still on b5 you exploit the pin/loose pieces; you equalize comfortably with active play." },
            ]},
          ],
        },
        {
          id: "b-alapin-black",
          title: "vs Alapin (2.c3)",
          intro: "When White plays 2.c3 (preparing d4 with a big center, and stopping your Open Sicilian), hit back with 2...Nf6 attacking e4. This forces White's hand and gives you active, easy development against the isolated d-pawn that often results.",
          lines: [
            { name: "2...Nf6", moves: [
              { san: "e4", c: "" },
              { san: "c5", c: "" },
              { san: "c3", c: "The Alapin. White wants d4 and a big center." },
              { san: "Nf6", c: "Hit e4 immediately and disrupt White's plan." },
              { san: "e5", c: "" },
              { san: "Nd5", c: "The knight sits well on d5 for now." },
              { san: "d4", c: "" },
              { san: "cxd4", c: "" },
              { san: "Nf3", c: "" },
              { san: "Nc6", c: "" },
              { san: "cxd4", c: "White gets an isolated d-pawn — a clear target for you." },
              { san: "d6", c: "Hit the e5 spearhead and open lines." },
              { san: "Bc4", c: "" },
              { san: "Nb6", c: "Gain a tempo on the bishop." },
              { san: "Bb3", c: "" },
              { san: "dxe5", c: "" },
              { san: "Nxe5", c: "" },
              { san: "Nxe5", c: "Trade into a comfortable game: blockade/attack the isolated d-pawn with ...Be7, ...O-O, ...Bf6/...Nd5. Fully equal, easy to play." },
            ]},
            { name: "2...d5 (alternative)", moves: [
              { san: "e4", c: "" },
              { san: "c5", c: "" },
              { san: "c3", c: "" },
              { san: "d5", c: "A solid alternative: open the position at once." },
              { san: "exd5", c: "" },
              { san: "Qxd5", c: "" },
              { san: "d4", c: "" },
              { san: "Nc6", c: "Develop and pressure d4." },
              { san: "Nf3", c: "" },
              { san: "Bg4", c: "Pin and pile on d4. You get easy, active development against White's slightly loose center." },
            ]},
          ],
        },
        {
          id: "b-closed-gp",
          title: "Closed Sicilian & Grand Prix",
          intro: "Two more anti-Sicilians to know. The Closed (2.Nc3, g3) is slow — mirror White with your own fianchetto and expand on the queenside with ...Rb8/...b5. The Grand Prix (f4 + Bc4) wants a quick kingside attack — neutralize it by putting your bishop on g7 and playing ...e6 to blunt the c4 bishop and prepare ...d5. (vs the Smith-Morra Gambit 2.d4 cxd4 3.c3, simply decline with 3...Nf6 4.e5 Nd5, transposing to Alapin-type play.)",
          lines: [
            { name: "Closed (2.Nc3 g3)", moves: [
              { san: "e4", c: "" },
              { san: "c5", c: "" },
              { san: "Nc3", c: "The Closed Sicilian — White avoids d4 entirely." },
              { san: "Nc6", c: "" },
              { san: "g3", c: "" },
              { san: "g6", c: "Mirror White's setup — you know these structures." },
              { san: "Bg2", c: "" },
              { san: "Bg7", c: "" },
              { san: "d3", c: "" },
              { san: "d6", c: "" },
              { san: "f4", c: "" },
              { san: "e6", c: "Flexible: prepares ...Nge7 and the ...d5 break, and keeps the position solid against White's kingside ambitions. Plan: ...Nge7, ...Rb8, ...b5-b4 expanding on the queenside where you're faster." },
            ]},
            { name: "Grand Prix (f4 + Bc4)", moves: [
              { san: "e4", c: "" },
              { san: "c5", c: "" },
              { san: "Nc3", c: "" },
              { san: "Nc6", c: "" },
              { san: "f4", c: "The Grand Prix Attack — White wants f4-f5 and a kingside attack." },
              { san: "g6", c: "Fianchetto: the g7 bishop is a great defender and attacker on the long diagonal." },
              { san: "Nf3", c: "" },
              { san: "Bg7", c: "" },
              { san: "Bc4", c: "Aiming at f7." },
              { san: "e6", c: "The key defensive move: blunts the c4 bishop, controls d5/f5, and prepares ...Nge7 and ...d5." },
              { san: "O-O", c: "" },
              { san: "Nge7", c: "Develop toward the kingside; the knight supports ...d5 and helps defend. Plan: ...O-O, ...d5, ...b6/...Bb7. You're solid and White's attack fizzles." },
            ]},
          ],
        },
      ],
    },

    // =====================================================================
    //  BLACK vs 1.d4 — Nimzo-Indian / Bogo-Indian
    // =====================================================================
    {
      id: "black-d4",
      title: "Black vs 1.d4: Nimzo / Bogo-Indian",
      heroColor: "b",
      blurb: "A respected, strategically rich answer to 1.d4. The Nimzo (3...Bb4) pins and often doubles White's pawns, fighting for the light squares. When White avoids 3.Nc3, the Bogo (3...Bb4+) gives a solid, easy companion system. Structures over memorization.",
      chapters: [
        {
          id: "d-nimzo-rubinstein",
          title: "Nimzo — Rubinstein (4.e3)",
          intro: "The most common Nimzo at every level. After 4.e3 you castle and strike the center with ...d5 and ...c5. The typical structures are the isolated queen's pawn (IQP) and hanging pawns — you play against them with ...b6, ...Bb7, ...Nc6, and pressure down the c- and d-files. Learn the plans, not 20 moves of theory.",
          lines: [
            { name: "Main: ...d5 & ...c5", moves: [
              { san: "d4", c: "" },
              { san: "Nf6", c: "Flexible — controls e4 and keeps options open." },
              { san: "c4", c: "" },
              { san: "e6", c: "Preparing ...Bb4 and ...d5; keeps the position classical." },
              { san: "Nc3", c: "White develops the knight — now the Nimzo!" },
              { san: "Bb4", c: "The Nimzo-Indian: pin the knight, fight for e4, and threaten to double White's pawns with ...Bxc3." },
              { san: "e3", c: "The Rubinstein — solid and most popular." },
              { san: "O-O", c: "King safety; keep the tension." },
              { san: "Bd3", c: "" },
              { san: "d5", c: "Strike the center." },
              { san: "Nf3", c: "" },
              { san: "c5", c: "Hit d4 too — the standard central counter." },
              { san: "O-O", c: "" },
              { san: "dxc4", c: "Clarify: White recaptures and you'll get an IQP / hanging-pawns battle." },
              { san: "Bxc4", c: "" },
              { san: "Nc6", c: "Develop and pressure d4. Plans: ...b6 + ...Bb7, ...cxd4, ...Be7/...Bd6 reroute, and play against White's hanging or isolated pawns. Comfortable equality with clear targets." },
            ]},
          ],
        },
        {
          id: "d-nimzo-classical",
          title: "Nimzo — Classical (4.Qc2)",
          intro: "White's most principled try: 4.Qc2 avoids the doubled pawns and bids for the bishop pair. You trade on c3, then immediately target the c4 pawn and the long light diagonal with ...d5, ...dxc4, ...b6 and ...Ba6. White gets the two bishops; you get a rock-solid structure and concrete pressure.",
          lines: [
            { name: "4...O-O & ...d5", moves: [
              { san: "d4", c: "" },
              { san: "Nf6", c: "" },
              { san: "c4", c: "" },
              { san: "e6", c: "" },
              { san: "Nc3", c: "" },
              { san: "Bb4", c: "" },
              { san: "Qc2", c: "The Classical — White wants to recapture on c3 with the queen and keep the pawns intact." },
              { san: "O-O", c: "" },
              { san: "a3", c: "Forcing the trade now." },
              { san: "Bxc3+", c: "" },
              { san: "Qxc3", c: "White has the bishop pair but no compensation yet — you'll fight on the light squares." },
              { san: "d5", c: "Challenge the center and open lines to c4." },
              { san: "Nf3", c: "" },
              { san: "dxc4", c: "Pull the queen onto an exposed square and set up ...b6/...Ba6 hitting c4." },
              { san: "Qxc4", c: "" },
              { san: "b6", c: "Prepare ...Ba6, harassing the queen and pressuring c4. Plans: ...Ba6, ...c5, ...Nbd7/...Nc6, ...Rc8. Solid and active — White's bishops have no targets." },
            ]},
          ],
        },
        {
          id: "d-nimzo-saemisch",
          title: "Nimzo — Sämisch (4.a3)",
          intro: "White immediately forces ...Bxc3 and bxc3, accepting doubled c-pawns to build a big center with f3/e4. Your strategy is classic Nimzo: blockade and besiege those doubled pawns. Play ...c5, ...Nc6, ...b6, ...Ba6 hammering c4, and ...Na5 — the c4 pawn is chronically weak. If you blunt his center, you're just better structurally.",
          lines: [
            { name: "Blockade the c-pawns", moves: [
              { san: "d4", c: "" },
              { san: "Nf6", c: "" },
              { san: "c4", c: "" },
              { san: "e6", c: "" },
              { san: "Nc3", c: "" },
              { san: "Bb4", c: "" },
              { san: "a3", c: "The Sämisch — White spends a tempo to grab the bishop pair and doubled-pawn center." },
              { san: "Bxc3+", c: "" },
              { san: "bxc3", c: "Now White has doubled c-pawns and a target on c4." },
              { san: "c5", c: "Fix the queenside — you want to blockade c4 and attack it." },
              { san: "e3", c: "" },
              { san: "Nc6", c: "Pressure d4." },
              { san: "Bd3", c: "" },
              { san: "O-O", c: "" },
              { san: "Ne2", c: "White prepares e4." },
              { san: "b6", c: "Prepare ...Ba6 (hitting c4 and trading White's good bishop) and ...Na5. Plans: ...Ba6, ...Na5 hammering c4, keep the center closed. You play against a permanent weakness." },
            ]},
          ],
        },
        {
          id: "d-nimzo-f3",
          title: "Nimzo — 4.f3 & sidelines",
          intro: "4.f3 (preparing a huge e4 center) and other 4th moves (4.Bg5, 4.g3) are less critical. Against 4.f3 strike the center with ...d5 before White completes e4; against 4.Bg5 play ...h6 and ...c5. The recurring theme: don't let White's center stabilize — hit it with ...d5 or ...c5 while he's slow.",
          lines: [
            { name: "4.f3 d5", moves: [
              { san: "d4", c: "" },
              { san: "Nf6", c: "" },
              { san: "c4", c: "" },
              { san: "e6", c: "" },
              { san: "Nc3", c: "" },
              { san: "Bb4", c: "" },
              { san: "f3", c: "Ambitious — White wants e4 and a big center, but it's slow and weakens the king." },
              { san: "d5", c: "Strike immediately before e4 arrives." },
              { san: "a3", c: "" },
              { san: "Bxc3+", c: "" },
              { san: "bxc3", c: "" },
              { san: "c5", c: "Pile on the center; White's structure is loose and his development is behind. You have an excellent game targeting c4/d4 and the weakened light squares." },
            ]},
            { name: "4.Bg5", moves: [
              { san: "d4", c: "" },
              { san: "Nf6", c: "" },
              { san: "c4", c: "" },
              { san: "e6", c: "" },
              { san: "Nc3", c: "" },
              { san: "Bb4", c: "" },
              { san: "Bg5", c: "The Leningrad — pins the f6 knight." },
              { san: "h6", c: "Question the bishop at once." },
              { san: "Bh4", c: "" },
              { san: "c5", c: "Hit the center; with ...g5 and ...Ne4 ideas available you get sharp, comfortable counterplay. Don't fear the pin — your dark-square pressure is strong." },
            ]},
          ],
        },
        {
          id: "d-bogo",
          title: "Bogo-Indian (3.Nf3 Bb4+)",
          intro: "When White plays 3.Nf3 (avoiding 3.Nc3 and your Nimzo), check with 3...Bb4+. It's solid, low-theory, and leads to sound positions. The standard plan after 4.Bd2 Qe7 is to trade the dark bishops and play the freeing ...e5 break. Easy to learn and very safe — your perfect Nimzo companion.",
          lines: [
            { name: "4.Bd2 Qe7", moves: [
              { san: "d4", c: "" },
              { san: "Nf6", c: "" },
              { san: "c4", c: "" },
              { san: "e6", c: "" },
              { san: "Nf3", c: "White sidesteps the Nimzo by delaying Nc3." },
              { san: "Bb4+", c: "The Bogo-Indian check." },
              { san: "Bd2", c: "The main reply." },
              { san: "Qe7", c: "Keep the bishop (avoiding a trade that helps White) and prepare ...Bxd2 on your terms plus ...e5." },
              { san: "g3", c: "" },
              { san: "Nc6", c: "Supporting the ...e5 break." },
              { san: "Bg2", c: "" },
              { san: "Bxd2+", c: "Trade now that it costs White a tempo to recapture with the knight." },
              { san: "Nbxd2", c: "" },
              { san: "d6", c: "Prepare ...e5." },
              { san: "O-O", c: "" },
              { san: "e5", c: "The freeing break — you equalize comfortably with a sound, easy-to-play position. Plans: ...O-O, ...Re8, ...a5, central play." },
            ]},
            { name: "4.Nbd2", moves: [
              { san: "d4", c: "" },
              { san: "Nf6", c: "" },
              { san: "c4", c: "" },
              { san: "e6", c: "" },
              { san: "Nf3", c: "" },
              { san: "Bb4+", c: "" },
              { san: "Nbd2", c: "Blocking the check with the knight (keeps the bishop pair if you trade)." },
              { san: "b6", c: "Fianchetto plan: pressure e4 and the long diagonal." },
              { san: "a3", c: "" },
              { san: "Bxd2+", c: "" },
              { san: "Bxd2", c: "" },
              { san: "Bb7", c: "Develop. Plans: ...O-O, ...d6, ...Nbd7, ...Ne4 fighting for the e4 square. Solid and flexible." },
            ]},
          ],
        },
        {
          id: "d-catalan",
          title: "vs Catalan / 3.g3",
          intro: "If White fianchettos with 3.g3 (the Catalan), the most reliable club answer is to grab the c4 pawn and hold it with the ...a6 system: ...d5, ...dxc4, ...a6, then ...b5 and ...Bb7. White gets pressure on the long diagonal; you get an extra pawn and a solid structure. If you'd rather keep it simple, ...Bb4+ also transposes to Bogo-like play.",
          lines: [
            { name: "Open Catalan with ...a6", moves: [
              { san: "d4", c: "" },
              { san: "Nf6", c: "" },
              { san: "c4", c: "" },
              { san: "e6", c: "" },
              { san: "g3", c: "The Catalan — White fianchettos to pressure your queenside and center." },
              { san: "d5", c: "Challenge the center." },
              { san: "Bg2", c: "" },
              { san: "dxc4", c: "Take the pawn — the Open Catalan." },
              { san: "Nf3", c: "" },
              { san: "a6", c: "The reliable system: hold the extra c4 pawn with ...b5 and develop the bishop to b7." },
              { san: "O-O", c: "" },
              { san: "Nc6", c: "Supports ...b5 and ...Rb8 ideas; sometimes ...Bd7-e8 reroutes. Plan: ...b5, ...Bb7, ...Be7, ...O-O. You're solid with an extra pawn and clear development." },
            ]},
            { name: "3...Bb4+ (simple)", moves: [
              { san: "d4", c: "" },
              { san: "Nf6", c: "" },
              { san: "c4", c: "" },
              { san: "e6", c: "" },
              { san: "g3", c: "" },
              { san: "Bb4+", c: "A simpler route — develop with a check and aim for Bogo-style play." },
              { san: "Bd2", c: "" },
              { san: "Be7", c: "Retreat (the inserted Bd2 slightly clogs White's setup) and head for a solid ...d5/...O-O structure. Low-theory and safe." },
            ]},
          ],
        },
        {
          id: "d-anti-d4",
          title: "London / Trompowsky & other systems",
          intro: "Not everyone plays 2.c4. Against system openings stay principled. London (2.Bf4): develop your bishop actively too and aim for ...c5/...e6 with quick development, even trading off White's prized bishop. Trompowsky (2.Bg5): play ...e6 and ...h6 to question the bishop. Against Colle/Veresov, just develop soundly with ...d5, ...e6, ...c5, ...Bd6/...Be7 — these systems pose no theoretical problems.",
          lines: [
            { name: "London (2.Bf4)", moves: [
              { san: "d4", c: "" },
              { san: "Nf6", c: "" },
              { san: "Bf4", c: "The London System — White plays a setup, not a theory battle." },
              { san: "e6", c: "Flexible; prepares ...c5, ...Bd6 (to trade White's good bishop), or ...b6." },
              { san: "e3", c: "" },
              { san: "c5", c: "Strike the center — the standard antidote to the London." },
              { san: "Nf3", c: "" },
              { san: "Bd6", c: "Offer to trade White's pride-and-joy dark-squared bishop." },
              { san: "Bg3", c: "" },
              { san: "O-O", c: "" },
              { san: "Nbd2", c: "" },
              { san: "b6", c: "Develop the bishop to b7 and play ...Bxg3 at a good moment, then ...Nc6/...Qe7 with a comfortable, equal game." },
            ]},
            { name: "Trompowsky (2.Bg5)", moves: [
              { san: "d4", c: "" },
              { san: "Nf6", c: "" },
              { san: "Bg5", c: "The Trompowsky — White pins before playing c4." },
              { san: "e6", c: "Solid and flexible; prepares ...h6 and ...c5/...Be7." },
              { san: "e4", c: "" },
              { san: "h6", c: "Question the bishop immediately." },
              { san: "Bxf6", c: "" },
              { san: "Qxf6", c: "You get the bishop pair and a sound position; ...d6, ...c5, ...Nc6 and ...Bd7/...g6 give you an easy, comfortable game." },
            ]},
          ],
        },
      ],
    },
  ],
};
